### ISSUE TITLE
Melhorias

### ISSUE THREAD

**Issue by kyriosdata** [matheuspiment/i-2018#1]
- Exercício 8 e 7 não fazem o que foi especificado.
- É preciso documentar métodos públicos, por exemplo, "main". 
- Reorganize seu repositório. Há alguma dificuldade para identificar exatamente onde cada tópico está implementado.
- O diretório docs não deveria existir aqui. Isso não faz parte do repositório.

**Comment by matheuspiment** [comment]
Correções ainda não realizadas:
* Exercício 8 e 7 não fazem o que foi especificado.
